project:
  type: website
  output-dir: docs

render:
      - index.qmd
      - ACP-Cours.qmd
      - CAH-Cours.qmd


website:
  title: "EXP3 : Stat. Multivariée"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ACP-Cours.qmd
      - CAH-Cours.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

includes:
  after_body: js/custom_javascript.html


