project:
  type: website
  output-dir: docs

render:
      - index.qmd
      - intro.qmd

website:
  title: "ACP-CAH"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - intro.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

includes:
  after_body: js/custom_javascript.html


