project:
  type: website
  output-dir: docs

render:
      - EXP3-Cours1-Intro.qmd
      - EXP3-Cours2-ACP.qmd
      - EXP3-Cours3-CAH.qmd       
      - EXP3-Exo1-ACP.qmd
      - EXP3-Exo2-AFC.qmd
      - EXP3-Exo3-ACM.qmd


website:
  title: "EXP3 : Statistique multivariée"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - EXP3-Cours1-Intro.qmd
      - EXP3-Cours2-ACP.qmd
      - EXP3-Cours3-CAH.qmd      
      - EXP3-Exo1-ACP.qmd
      - EXP3-Exo2-AFC.qmd
      - EXP3-Exo3-ACM.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

includes:
  after_body: js/custom_javascript.html


