project:
  type: website
  output-dir: docs

render:
      - index.qmd
      - Cours-AFC.qmd
      - Cours-ACM.qmd      
      - Cours-ACP.qmd
      - Cours-CAH.qmd
      - Exo-CEDEAO.qmd
      - Exo-AFRIQUE.qmd

website:
  title: "EXP3 : Stat. Multivariée"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Cours-AFC.qmd
      - Cours-ACM.qmd       
      - Cours-ACP.qmd
      - Cours-CAH.qmd
      - Exo-CEDEAO.qmd
      - Exo-AFRIQUE.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

includes:
  after_body: js/custom_javascript.html


