<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>EXP3 : Stat. Multivariée - EXO : CEDEAO</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">EXP3 : Stat. Multivariée</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Cours-ACP.html">COURS : ACP</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Cours-Classif.html">COURS : Classification</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Exo-CEDEAO.html" aria-current="page">EXO : CEDEAO</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tableau-1-taille-et-développement" id="toc-tableau-1-taille-et-développement" class="nav-link active" data-scroll-target="#tableau-1-taille-et-développement">Tableau 1 : Taille et développement</a>
  <ul class="collapse">
  <li><a href="#préparation-des-données" id="toc-préparation-des-données" class="nav-link" data-scroll-target="#préparation-des-données">Préparation des données</a></li>
  <li><a href="#analyse-en-composante-pricipale-acp" id="toc-analyse-en-composante-pricipale-acp" class="nav-link" data-scroll-target="#analyse-en-composante-pricipale-acp">Analyse en composante pricipale (ACP)</a></li>
  <li><a href="#classification-ascendante-hiérarchique-cah" id="toc-classification-ascendante-hiérarchique-cah" class="nav-link" data-scroll-target="#classification-ascendante-hiérarchique-cah">Classification Ascendante Hiérarchique (CAH)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">EXO : CEDEAO</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE</code></pre>
</div>
</div>
<p>L’objectif de ce document est de présenter des exemples d’application <strong>non technique</strong> des méthodes d’analyse factorielle et de classification. Il s’agit donc de faire saisir les objectifs des deux méthodes que l’on peut résumer en première analyse comme suit :</p>
<ol type="1">
<li><p><strong>Réduction d’un ensemble de variables</strong> à un petit nombre de <strong>facteurs</strong> qui les résument au mieux. Chaque facteur est composée de variables corrélées entre elles donc partiellement redondantes. En revanche les facteurs sont orthogonaux c’est-à-dire indépendants entre eux.</p></li>
<li><p><strong>Réduction d’un ensemble d’individus</strong> à un petit nombre de <strong>classes</strong> qui regroupent les individus les plus ressemblants entre eux et séparent les plus différents.</p></li>
</ol>
<p>Nous allons prendre comme terrain d’application un rapport publié en 2021 sur les forces et les faiblesses des pays de la CEDEAO <span class="citation" data-cites="vedie2021forces">[@vedie2021forces]</span>.</p>
<p>L’auteur du rapport, P.H. Vedie cherche à identifier <em>ce qui rapproche et ce qui différencie</em> les pays de la CEDEAO. Il va donc proposer successivemet différents <strong>tableaux</strong> dont les lignes correspondent aux pays de la CEDEAO et les colonnes aux critères retenus pour examiner les ressemblances et les différences entre ces pays.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/carte1-1.png" class="img-fluid" width="768"></p>
</div>
</div>
<section id="tableau-1-taille-et-développement" class="level2">
<h2 class="anchored" data-anchor-id="tableau-1-taille-et-développement">Tableau 1 : Taille et développement</h2>
<p>Le premier tableau présenté par l’auteur du rapport combine deux <strong>variables de stock</strong> visant à mesurer la taille des pays et deux <strong>variables de rapport</strong> visant à évaluer leur niveau de développement :</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/tab1.png" class="img-fluid figure-img" width="400"></p>
<p></p><figcaption class="figure-caption">Source : Vedie PH, 2021</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="préparation-des-données" class="level3">
<h3 class="anchored" data-anchor-id="préparation-des-données">Préparation des données</h3>
<p>Après l’avoir saisi à l’aide d’un tableur,on importe ce tableau dans R afin de pouvoir effectuer des traitements statistiques dessus. On simplifie le nom des variables et on ajoute pour chaque pays un code ISO3 permetant de cartographier éventuellement les résultats de nos analyses.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">Code</th>
<th style="text-align: left;">Pays</th>
<th style="text-align: right;">SUP</th>
<th style="text-align: right;">POP</th>
<th style="text-align: right;">IDH</th>
<th style="text-align: right;">ALP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BEN</td>
<td style="text-align: left;">Bénin</td>
<td style="text-align: right;">113000</td>
<td style="text-align: right;">11.80</td>
<td style="text-align: right;">0.5200</td>
<td style="text-align: right;">32.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">BFA</td>
<td style="text-align: left;">Burkina Faso</td>
<td style="text-align: right;">274000</td>
<td style="text-align: right;">20.30</td>
<td style="text-align: right;">0.4340</td>
<td style="text-align: right;">34.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CPV</td>
<td style="text-align: left;">Cap-Vert</td>
<td style="text-align: right;">4000</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.6610</td>
<td style="text-align: right;">86.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">CIV</td>
<td style="text-align: left;">Côte d’Ivoire</td>
<td style="text-align: right;">322000</td>
<td style="text-align: right;">25.70</td>
<td style="text-align: right;">0.5163</td>
<td style="text-align: right;">43.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GMB</td>
<td style="text-align: left;">Gambie</td>
<td style="text-align: right;">11000</td>
<td style="text-align: right;">2.30</td>
<td style="text-align: right;">0.4660</td>
<td style="text-align: right;">42.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">GHA</td>
<td style="text-align: left;">Ghana</td>
<td style="text-align: right;">239000</td>
<td style="text-align: right;">30.40</td>
<td style="text-align: right;">0.5960</td>
<td style="text-align: right;">71.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GIN</td>
<td style="text-align: left;">Guinée</td>
<td style="text-align: right;">246000</td>
<td style="text-align: right;">12.84</td>
<td style="text-align: right;">0.4663</td>
<td style="text-align: right;">32.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNB</td>
<td style="text-align: left;">Guinée-Bissau</td>
<td style="text-align: right;">36000</td>
<td style="text-align: right;">1.90</td>
<td style="text-align: right;">0.4610</td>
<td style="text-align: right;">45.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LBR</td>
<td style="text-align: left;">Libéria</td>
<td style="text-align: right;">111000</td>
<td style="text-align: right;">4.90</td>
<td style="text-align: right;">0.4650</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLI</td>
<td style="text-align: left;">Mali</td>
<td style="text-align: right;">1240000</td>
<td style="text-align: right;">19.70</td>
<td style="text-align: right;">0.4270</td>
<td style="text-align: right;">33.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NER</td>
<td style="text-align: left;">Niger</td>
<td style="text-align: right;">1267000</td>
<td style="text-align: right;">23.30</td>
<td style="text-align: right;">0.3770</td>
<td style="text-align: right;">30.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">NGA</td>
<td style="text-align: left;">Nigeria</td>
<td style="text-align: right;">924000</td>
<td style="text-align: right;">201.00</td>
<td style="text-align: right;">0.5340</td>
<td style="text-align: right;">51.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SEN</td>
<td style="text-align: left;">Sénégal</td>
<td style="text-align: right;">197000</td>
<td style="text-align: right;">16.30</td>
<td style="text-align: right;">0.5050</td>
<td style="text-align: right;">51.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">SLE</td>
<td style="text-align: left;">Sierra Leone</td>
<td style="text-align: right;">72000</td>
<td style="text-align: right;">7.80</td>
<td style="text-align: right;">0.4380</td>
<td style="text-align: right;">32.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TGO</td>
<td style="text-align: left;">Togo</td>
<td style="text-align: right;">57000</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: right;">0.5130</td>
<td style="text-align: right;">63.7</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="paramètres-principaux" class="level4">
<h4 class="anchored" data-anchor-id="paramètres-principaux">Paramètres principaux</h4>
<p>Les paramètres principaux des quatre variables permettent de se faire une idée plus précise de la forme de leurs distributions.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Paramètres principaux</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">SUP</th>
<th style="text-align: right;">POP</th>
<th style="text-align: right;">IDH</th>
<th style="text-align: right;">ALP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Minimum</td>
<td style="text-align: right;">4000</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.377</td>
<td style="text-align: right;">30.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maximum</td>
<td style="text-align: right;">1267000</td>
<td style="text-align: right;">201.0</td>
<td style="text-align: right;">0.661</td>
<td style="text-align: right;">86.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Médiance</td>
<td style="text-align: right;">197000</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">0.466</td>
<td style="text-align: right;">43.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Moyenne</td>
<td style="text-align: right;">340867</td>
<td style="text-align: right;">25.5</td>
<td style="text-align: right;">0.492</td>
<td style="text-align: right;">46.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ecart-type</td>
<td style="text-align: right;">432928</td>
<td style="text-align: right;">49.5</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">17.1</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="standardisation-du-tableau" class="level4">
<h4 class="anchored" data-anchor-id="standardisation-du-tableau">Standardisation du tableau</h4>
<p>Les quatre variables présentes dans le tableau sont difficiles à comparer entre elles car elles utilisent différentes unités de mesure. Si l’on veut comparer les pays de la CEDEAO entre eux il est plus simple de commencer par standardiser les variables à l’aide d’une double opération de <strong>centrage</strong> par la moyenne et de <strong>réduction</strong> par l’écart-type.</p>
<p><span class="math inline">\(X'_i = \frac {X_i - {moy}(X)} {{écart-type}(X)}\)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">SUP</th>
<th style="text-align: right;">POP</th>
<th style="text-align: right;">IDH</th>
<th style="text-align: right;">ALP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BEN</td>
<td style="text-align: right;">-0.53</td>
<td style="text-align: right;">-0.28</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">-0.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">BFA</td>
<td style="text-align: right;">-0.15</td>
<td style="text-align: right;">-0.10</td>
<td style="text-align: right;">-0.82</td>
<td style="text-align: right;">-0.70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CPV</td>
<td style="text-align: right;">-0.78</td>
<td style="text-align: right;">-0.50</td>
<td style="text-align: right;">2.39</td>
<td style="text-align: right;">2.36</td>
</tr>
<tr class="even">
<td style="text-align: left;">CIV</td>
<td style="text-align: right;">-0.04</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">-0.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GMB</td>
<td style="text-align: right;">-0.76</td>
<td style="text-align: right;">-0.47</td>
<td style="text-align: right;">-0.37</td>
<td style="text-align: right;">-0.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">GHA</td>
<td style="text-align: right;">-0.24</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">1.47</td>
<td style="text-align: right;">1.46</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GIN</td>
<td style="text-align: right;">-0.22</td>
<td style="text-align: right;">-0.25</td>
<td style="text-align: right;">-0.36</td>
<td style="text-align: right;">-0.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNB</td>
<td style="text-align: right;">-0.70</td>
<td style="text-align: right;">-0.48</td>
<td style="text-align: right;">-0.44</td>
<td style="text-align: right;">-0.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LBR</td>
<td style="text-align: right;">-0.53</td>
<td style="text-align: right;">-0.42</td>
<td style="text-align: right;">-0.38</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLI</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">-0.12</td>
<td style="text-align: right;">-0.92</td>
<td style="text-align: right;">-0.79</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NER</td>
<td style="text-align: right;">2.14</td>
<td style="text-align: right;">-0.04</td>
<td style="text-align: right;">-1.63</td>
<td style="text-align: right;">-0.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">NGA</td>
<td style="text-align: right;">1.35</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: right;">0.59</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SEN</td>
<td style="text-align: right;">-0.33</td>
<td style="text-align: right;">-0.19</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">SLE</td>
<td style="text-align: right;">-0.62</td>
<td style="text-align: right;">-0.36</td>
<td style="text-align: right;">-0.76</td>
<td style="text-align: right;">-0.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TGO</td>
<td style="text-align: right;">-0.66</td>
<td style="text-align: right;">-0.45</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">1.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Le tabeau des valeurs standardisées permet de repérer un certain nombre de valeurs exceptionnelles qui sortent de l’intervalle de confiance à 95% [-2 ; +2]. La plus remarquable de ces valeurs exceptionnelles est celle du Nigéria dont la population se situe à 3.55 écarts-type de la moyenne des pays de la CEDEAO. On repère également la très grande superficie du Niger (+2.14) et du Mali (+2.08) par rapport à celles des autres pays. Enfin, on note le caractère exceptionnel du Cap Vert en matière d’IDH (+2.39) et d’alphabétisation (+2.36).</p>
</section>
<section id="analyse-des-corrélations" class="level4">
<h4 class="anchored" data-anchor-id="analyse-des-corrélations">Analyse des corrélations</h4>
<p>L’analyse de la matrice des corrélations va nous permettre de savoir si les quatre variables retenues sont redondantes entre elles (forte corrélation positve ou négative) ou bien si elles sont réellement indépendantes (faible corrélation). On utilise ici la fonction <code>ggpairs()</code>du package GGally afin de pouvoir visualiser no seulement les coefficients de corrélation mais aussi leur significativité et la forme du nauage de points associé.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>On observe qu’il existe une corrélation positive forte (+0.881) et très significative (p &lt; 0.001) entre les variables IDH et ALP ce qui n’a rien d’étonnnant puisque l’alphabétisation est une des trois composantes de l’Indicateur de Développement Humain. Par contre on ne trouve pas d’autres corrélations significatives entre les autres indicateurs. Il y a certes une corrélation positive entre population et superficie (+0.466) mais sa significativité est faible en raison des exceptions constituées par le Mali et le Niger qui ont une population faible relativement à leur superficie. On note enfin une relation négative assez forte entre superficie et IDH (-0.415), sans doute explicable par le retard de développement des pays enclavés du Sahel, mais sa significativité demeure faible.</p>
</section>
</section>
<section id="analyse-en-composante-pricipale-acp" class="level3">
<h3 class="anchored" data-anchor-id="analyse-en-composante-pricipale-acp">Analyse en composante pricipale (ACP)</h3>
<p>L’analyse en composante principale nous permet de réduire le nombre de variable en regroupant entre elles les plus corréllées positivement ou négativement. On cherche donc à identifier des “super-variables” qui résument plusieurs autres à la fois.</p>
<section id="valeurs-propres" class="level4">
<h4 class="anchored" data-anchor-id="valeurs-propres">Valeurs propres</h4>
<p>Au départ chacune de nos quatre variables représente 25% de l’information totale du tableau puisque nous les avons standardisées pour leur donner des contributions égales. Quelle est la part de l’information totale que représentent les facteurs mis à jour par l’ACP ?</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Tableau des valeurs propres</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Valeur propre</th>
<th style="text-align: right;">% variance</th>
<th style="text-align: right;">% variance cumulée</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">comp 1</td>
<td style="text-align: right;">2.14</td>
<td style="text-align: right;">53.57</td>
<td style="text-align: right;">53.57</td>
</tr>
<tr class="even">
<td style="text-align: left;">comp 2</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">33.90</td>
<td style="text-align: right;">87.47</td>
</tr>
<tr class="odd">
<td style="text-align: left;">comp 3</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">9.99</td>
<td style="text-align: right;">97.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">comp 4</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">2.54</td>
<td style="text-align: right;">100.00</td>
</tr>
</tbody>
</table>
</div>
</div>
<ul>
<li>Le <strong>premier facteur</strong> résume à lui seul plus de la moitié de l’information (53.6%) ce qui veut dire qu’il résume l’équivalent de plus de deux des variables de départ (ce qu’exprime sa valeur propre de 2.14).</li>
<li>Le <strong>second facteur</strong> résume quant à lui 33.9% de l’information, ce qui est plus que l’une des variables de départ et lui donne une valeur propre de 1.36.</li>
</ul>
<p>A eux deux, ces facteurs résument donc 87.5% de l’information contenue dans le tableau et sont donc suffisant pour nous livrer l’essentiel des résultats importants sur la taille et le développement des pays de la CEDEAO. Les facteurs 3 et 4 ont d’ailleurs des valeurs propres très inférieur à 1 ce qui signifie qu’il n’apportent plus que des renseignements secondaires.</p>
</section>
<section id="corrélation-des-variables-avec-les-facteurs" class="level4">
<h4 class="anchored" data-anchor-id="corrélation-des-variables-avec-les-facteurs">Corrélation des variables avec les facteurs</h4>
<p>Nous allons maintenant visualiser la corrélation de chacune des variables avec les facteurs afin de pouvoir les interpréter.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><p>Le <strong>premier facteur</strong> est très fortement corrrélé positivement avec les variables IDH et Alphabétisation et exprime donc le <strong>niveau général de développement des pays</strong> de la CEDEAO. La variable population est orthogonale au premier facteur, ce qui signifie qu’il n’y a aucune relation entre le niveau de développement et la population des pays. En revanche la variable superficie est légèrement corrélée négativement avec ce premier axe, ce qui est lié au fait que les grands pays du Sahel (Mali, Niger) sont aussi ceux qui ont les niveau d’IDH et d’alphabétisation parmi les plus faibles.</p></li>
<li><p>Le <strong>second facteur</strong> est très fortement corrélé avec la population ainsi que - mais à un moindre degré - avec la superficie des pays. Il exprime donc la <strong>taille globale des pays</strong> à partir d’une combinaison de deux variables.</p></li>
</ul>
<p>L’interprétation des deux facteurs est ici très simple car l’auteur du tableau avait manifestement choisi ses variables pour combiner des effets de taille (2 critères) et de développement (2 critères). Mais lorsque les tableaux sont plus complexes, il peut être utile de recourrir à des outils d’analyse plus précis du type du tableau ci-dessous que nous ne détaillerons pas dans l’immédiat.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Relations entre variables et facteurs</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Corrélation (F1)</th>
<th style="text-align: right;">Contribution (F1)</th>
<th style="text-align: right;">Cosinus2 (F1)</th>
<th style="text-align: right;">Corrélation (F2)</th>
<th style="text-align: right;">Contribution (F2)</th>
<th style="text-align: right;">Cosinus2 (F2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SUP</td>
<td style="text-align: right;">-0.668</td>
<td style="text-align: right;">20.8</td>
<td style="text-align: right;">0.447</td>
<td style="text-align: right;">0.592</td>
<td style="text-align: right;">25.9</td>
<td style="text-align: right;">0.351</td>
</tr>
<tr class="even">
<td style="text-align: left;">POP</td>
<td style="text-align: right;">-0.132</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.017</td>
<td style="text-align: right;">0.919</td>
<td style="text-align: right;">62.3</td>
<td style="text-align: right;">0.845</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IDH</td>
<td style="text-align: right;">0.923</td>
<td style="text-align: right;">39.8</td>
<td style="text-align: right;">0.852</td>
<td style="text-align: right;">0.305</td>
<td style="text-align: right;">6.9</td>
<td style="text-align: right;">0.093</td>
</tr>
<tr class="even">
<td style="text-align: left;">ALP</td>
<td style="text-align: right;">0.909</td>
<td style="text-align: right;">38.6</td>
<td style="text-align: right;">0.826</td>
<td style="text-align: right;">0.259</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">0.067</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="coordonnées-des-individus-sur-les-facteurs" class="level4">
<h4 class="anchored" data-anchor-id="coordonnées-des-individus-sur-les-facteurs">Coordonnées des individus sur les facteurs</h4>
<p>Maintenant que nous avons sélectionné nos facteurs et que nous leur avons donnée une interprétation, nous pouvons analyser la position des pays de la CEDEA par rapport à ces deux super-variables.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>La <strong>position du Nigéria</strong> au sommet de l’axe 2 résulte naturellement de sa population exceptionellement forte par rapport à celle des autres pays. Son éloignement par rapport aux autres points ne fait que restituer de façon géométrique ce que nous avions observé à l’aide du tableau des valeurs standardisés.</li>
<li>Les <strong>pays situés à droite du graphiques</strong> (<em>Cap Vert, Ghana</em>) sont ceux qui ont les plus forts niveaux d’IDH et les plus forts niveaux d’alphabétisation.</li>
<li>Les <strong>pays situés à gauche du graphique</strong> (<em>Mali, Niger</em>) sont au contraire ceux qui ont les plus faibles niveaux de développement combinée avec une superficie importante.</li>
<li>Les <strong>pays situés autour du centre du graphique</strong> sont ceux dont les caractéristiques sont assez proches de la moyenne des pays de la CEDEAO. Le pays le plus typique est de ce point de vue la Côte d’Ivoire qui est positionnée pratiquement au croisement des deux axes. Il reste néanmoins possible d’analyser les différences internes au “paquet” central. Par exemple la Gambie ou la Sierra Léone sont situées plus pas que le Sénégal ou le Bénin car elles ont une population plus petite. Le Burkina Faso est situé plus à gauche que le Togo car il a un IDH et une alphabétisation plus faible.</li>
</ul>
<p>Comme dans le cas des variables, on peut utiliser un tableau plus détaillé afin d’interpréter la position des pays sur les axes et leur contribution à la création de ces derniers :</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Relations entre individus et facteurs</caption>
<colgroup>
<col style="width: 3%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 17%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Coordonnées (F1)</th>
<th style="text-align: right;">Contribution (F1)</th>
<th style="text-align: right;">Cosinus2 (F1)</th>
<th style="text-align: right;">Coordonnées (F2)</th>
<th style="text-align: right;">Contribution (F2)</th>
<th style="text-align: right;">Cosinus2 (F2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BEN</td>
<td style="text-align: right;">-0.001</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.586</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">0.267</td>
</tr>
<tr class="even">
<td style="text-align: left;">BFA</td>
<td style="text-align: right;">-0.921</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">0.639</td>
<td style="text-align: right;">-0.557</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">0.233</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CPV</td>
<td style="text-align: right;">3.548</td>
<td style="text-align: right;">39.2</td>
<td style="text-align: right;">0.936</td>
<td style="text-align: right;">0.390</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">CIV</td>
<td style="text-align: right;">0.140</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.125</td>
<td style="text-align: right;">0.037</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GMB</td>
<td style="text-align: right;">-0.015</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.947</td>
<td style="text-align: right;">4.4</td>
<td style="text-align: right;">0.827</td>
</tr>
<tr class="even">
<td style="text-align: left;">GHA</td>
<td style="text-align: right;">2.037</td>
<td style="text-align: right;">12.9</td>
<td style="text-align: right;">0.855</td>
<td style="text-align: right;">0.706</td>
<td style="text-align: right;">2.4</td>
<td style="text-align: right;">0.103</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GIN</td>
<td style="text-align: right;">-0.679</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">0.418</td>
<td style="text-align: right;">-0.626</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">0.355</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNB</td>
<td style="text-align: right;">0.053</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">-0.892</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">0.809</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LBR</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">-0.723</td>
<td style="text-align: right;">2.6</td>
<td style="text-align: right;">0.812</td>
</tr>
<tr class="even">
<td style="text-align: left;">MLI</td>
<td style="text-align: right;">-2.097</td>
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">0.703</td>
<td style="text-align: right;">0.560</td>
<td style="text-align: right;">1.5</td>
<td style="text-align: right;">0.050</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NER</td>
<td style="text-align: right;">-2.693</td>
<td style="text-align: right;">22.6</td>
<td style="text-align: right;">0.829</td>
<td style="text-align: right;">0.425</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">0.021</td>
</tr>
<tr class="even">
<td style="text-align: left;">NGA</td>
<td style="text-align: right;">-0.403</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.010</td>
<td style="text-align: right;">3.833</td>
<td style="text-align: right;">72.2</td>
<td style="text-align: right;">0.925</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SEN</td>
<td style="text-align: right;">0.503</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.832</td>
<td style="text-align: right;">-0.202</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.134</td>
</tr>
<tr class="even">
<td style="text-align: left;">SLE</td>
<td style="text-align: right;">-0.726</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">0.267</td>
<td style="text-align: right;">-1.024</td>
<td style="text-align: right;">5.2</td>
<td style="text-align: right;">0.532</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TGO</td>
<td style="text-align: right;">1.215</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">0.763</td>
<td style="text-align: right;">-0.394</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.080</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="classification-ascendante-hiérarchique-cah" class="level3">
<h3 class="anchored" data-anchor-id="classification-ascendante-hiérarchique-cah">Classification Ascendante Hiérarchique (CAH)</h3>
<p>On peut poursuivre l’analyse en réalisant une classificiation des pays en fonction de leur ressemblance selon le critère de Ward.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Exo-CEDEAO_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>